import testinfra

def test_hosts_file(File):
    f = File('/etc/hosts')

    assert f.exists
    assert f.user == 'root'
    assert f.group == 'root'


def test_motd_file(File):
    f = File('/etc/motd')

    assert f.exists
    assert f.contains('automatically generated by Ansible')
